### ISSUE TITLE
Running pod with nfs-ganesha without priviliged or extra capabilities

### ISSUE THREAD

**Issue by bmbferreira** [nfs-ganesha/nfs-ganesha#426]
Hi, I'm trying to use nfs-ganesha to run an nfs-server inside a kubernetes cluster but all the examples that I see either run the container as privileged or add capabilities like [DAC_READ_SEARCH](http://man7.org/linux/man-pages/man7/capabilities.7.html). 

For instance, I'm trying to run this example and it only works only I run the nfs-server container as privileged:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-unique-id-namespace
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: worker-unique-id-namespace
  name: job-analysis-1234567890abcdef
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      restartPolicy: Never
      volumes:
        - name: nfs-volume
          emptyDir: {}
      initContainers:
      - name: cloner
        image: emblica/git-cloner:latest
        imagePullPolicy: Always
        env:
        - name: REPOSITORY_URL
          value: git://github.com/codacy/codacy-pmdjava
        ports:
        - protocol: TCP
          containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/git
      containers:
      - name: nfs-server
        image: mitcdh/nfs-ganesha
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbindtcp
            containerPort: 111
            protocol: TCP
          - name: rpcbindudp
            containerPort: 111
            protocol: UDP
          - name: portone
            containerPort: 38465
          - name: porttwo
            containerPort: 38466
          - name: portthree
            containerPort: 38467
          - name: portfour
            containerPort: 662  
        securityContext:
          privileged: true
        volumeMounts:
          - name: nfs-volume
            mountPath: /export
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs
  namespace: worker-unique-id-namespace
spec:
  volumes:
    - name: nfs-volume
      nfs: 
        # replace by the pod IP
        server: 172.17.0.4
        path: /export
  containers:
    - name: app
      image: ubuntu:xenial

      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-volume
          mountPath: /repo

      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 99999; done"]

```

Otherwise I can't mount the volume on the client pod. I get this output when doing kubectl describe:

```
kubectl describe pod pod-using-nfs --namespace worker-unique-id-namespace
Name:               pod-using-nfs
Namespace:          worker-unique-id-namespace
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.0.2.15
Start Time:         Tue, 28 May 2019 11:06:48 +0100
Labels:             <none>
Annotations:        <none>
Status:             Pending
IP:
Containers:
  app:
    Container ID:
    Image:         alpine
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do sleep 99999; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /repo from nfs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-whqhl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  nfs-volume:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    172.17.0.4
    Path:      /export
    ReadOnly:  false
  default-token-whqhl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-whqhl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    55s   default-scheduler  Successfully assigned worker-unique-id-namespace/pod-using-nfs to minikube
  Warning  FailedMount  45s   kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-ra6a8f14af9fb43a39aac9bf3911d2268.scope
mount.nfs: requested NFS version or transport protocol is not supported
  Warning  FailedMount  45s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-rbe2aad4851244beb9d32534dd8e3d09c.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
  Warning  FailedMount  44s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-rc8be62f5a1494ad2bdf54759db07bfcb.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
  Warning  FailedMount  41s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-r82c7198989e94a10b22bc5952daf3d71.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
  Warning  FailedMount  37s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-r957c87f65ec1489da3037fca615a6eb2.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
  Warning  FailedMount  29s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-r0ac1b7e1aeed49b2831cfd2b2e6c1eb7.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
  Warning  FailedMount  13s  kubelet, minikube  MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume --scope -- mount -t nfs 172.17.0.4:/export /var/lib/kubelet/pods/4e8bf83f-8130-11e9-802a-08002718f665/volumes/kubernetes.io~nfs/nfs-volume
Output: Running scope as unit: run-re76854995a5d43e392daae43c3991815.scope
mount.nfs: access denied by server while mounting 172.17.0.4:/export
```

Also, I'm using this image to test this: https://hub.docker.com/r/mitcdh/nfs-ganesha/dockerfile/.

I know that this isn't really an issue on the nfs-ganesha project but I tried to find on the documentation something related to security requirements etc and searched other examples of nfs-ganesha running on containers but everyone seems to be using privileged or extra capabilities. What am I missing here? What are the requirements to run nfs-ganesha with minimum permissions on the container? Thanks.
