### ISSUE TITLE
Resource temporarily unavailable on export while using Docker Volumes

### ISSUE THREAD

**Issue by manuelchichi** [nfs-ganesha/nfs-ganesha#733]
**Summary**
I am currently trying to set up a Ganesha server over a Docker container with a volume. When I see the logs, the export is not added to the list. I have tried several images from different sources and the outcome is the same. The only way to make it work is if I don't use the volume (or bind mount) over the exported folder.

**Logs**
```
2021-08-17 20:50:25 : e76d8f69af1e : ganesha.nfsd : [none] FSAL :CRIT :resolve_posix_filesystem(/exports) returned Resource temporarily unavailable (11)
2021-08-17 20:50:25 : e76d8f69af1e : ganesha.nfsd : [none] FSAL :INFO :Mapping 11 to ERR_FSAL_DELAY
2021-08-17 20:50:25 : e76d8f69af1e : ganesha.nfsd : [none] FSAL :MAJ :Failed to call create_export on underlying FSAL VFS
2021-08-17 20:50:25 : e76d8f69af1e : ganesha.nfsd : [none] FSAL :INFO :FSAL VFS now unused
2021-08-17 20:50:25 : e76d8f69af1e : ganesha.nfsd : [none] CONFIG :CRIT :Could not create export for (/exports) to (/exports)
```

**Ganesha conf file**
```
EXPORT {
    # Export Id (mandatory, each EXPORT must have a unique Export_Id)
    Export_Id = 1;

    # Exported path (mandatory)
    Path = "/exports";

    # Pseudo Path (required for NFS v4)
    Pseudo = "/exports";

    # Access control options
    Access_Type = NONE;
    #Access_Type = RW;
    Squash = No_Root_Squash;

    # NFS protocol options
    Transports = UDP, TCP;
    Protocols = 4;
    SecType = sys;
    Disable_ACL = false;

    # changed to false, otherwise normal users can't access directories where gid=0
    Manage_Gids = false;

    #to test disable getattr cache
    #Attr_Expiration_Time = 0;

    Anonymous_uid = 65534;
    Anonymous_gid = 65534;

    CLIENT {
      Clients = 192.168.0.0/16,10.0.0.0/8;
      Access_Type = RW;
    }

    Filesystem_id = 1.1;

    # Exporting FSAL
    FSAL {
      name = VFS;
    }
}
```
**Relevant mounted filesystem in the container**
```
mount
/dev/sda1 on /exports type ext4 (rw,relatime,discard,errors=remount-ro)
```

**Docker Compose file that I am using**
```
version: "3.8" 

volumes:
  nfs-data:

services:
  nfs-server:
    image: "izdock/nfs-ganesha:3.4" 
    volumes:
       - nfs-data:/exports
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment: 
      - CLIENT_LIST=192.168.0.0/16,10.0.0.0/8
      - LOG_LEVEL=DEBUG
    ports:
      - "111:111" 
      - "2049:2049" 
```

**Versions**
NFS Ganesha version: 3.4 (also 3.5)
Docker Engine CE:  20.10.8
OS: Ubuntu 20.04

I am not sure if there is something else missing or if am doing something wrong.

**Comment by dang** [comment]
What error message came directly before the one you listed?  There 
should have been one that tells us what call actually returned EAGAIN.

My best guess is that there's a CAP issue.  In general, Ganesha using 
FSAL_VFS needs to run in a privileged container do succeed.  I see 
you've added several CAPs, but I'm not sure that's all the ones we need.

Daniel

**Comment by manuelchichi** [comment]
Daniel, thank you for the quick answer.

Here are the [full logs](https://github.com/nfs-ganesha/nfs-ganesha/files/7009619/ganesha.log) of the Ganesha container. I don't see any other error in there.

Regards the required CAPs. I have tried running the container with "privileged: true" and the "ALL" capability set and I get the same results.

Also, I was able to run it successfully but by [creating a new virtual block device](https://www.thegeekdiary.com/how-to-create-virtual-block-device-loop-device-filesystem-in-linux/) and changing the driver opts in the Docker-Compose like this.

```
volumes:
  nfs-data:
    driver_opts:
      type: ext4
      device: /dev/loop100 # Block device path
```

Commands to create the virtual block device.
```
dd if=/dev/zero of=/tmp/disk bs=1M count=100
losetup /dev/loop100 /tmp/disk 
mkfs.ext4 /dev/loop100
```

Let me know if you see something!
